const avenueProfileListConstants = {
    AVENUE_PROFILELIST: "AVENUE_PROFILELIST",
    AVENUE_PROFILELIST_FETCHING: "AVENUE_PROFILELIST_FETCHING",
    AVENUE_PROFILELIST_ERROR: "AVENUE_PROFILELIST_ERROR",
}

export default avenueProfileListConstants;