const entertainmentsConstants = {
    ENTERTAINMENTS_PROFILELIST: "ENTERTAINMENTS_PROFILELIST",
    ENTERTAINMENTS_PROFILELIST_FETCHING: "ENTERTAINMENTS_PROFILELIST_FETCHING",
    ENTERTAINMENTS_PROFILELIST_ERROR: "ENTERTAINMENTS_PROFILELIST_ERROR",
}

export default entertainmentsConstants;