const experienceProfileListConstants = {
    EXPERIENCES_PROFILELIST: "EXPERIENCES_PROFILELIST",
    EXPERIENCES_PROFILELIST_FETCHING: "EXPERIENCES_PROFILELIST_FETCHING",
    EXPERIENCES_PROFILELIST_ERROR: "EXPERIENCES_PROFILELIST_ERROR",
}

export default experienceProfileListConstants;