const experiencesStatesConstants = {
    EXPERIENCES_STATES: "EXPERIENCES_STATES",
    EXPERIENCES_STATES_FETCHING: "EXPERIENCES_STATES_FETCHING",
    EXPERIENCES_STATES_ERROR: "EXPERIENCES_STATES_ERROR",
}

export default experiencesStatesConstants;