const magicTownsProfileListConstants = {
    MAGICTOWNS_PROFILELIST: "MAGICTOWNS_PROFILELIST",
    MAGICTOWNS_PROFILELIST_FETCHING: "MAGICTOWNS_PROFILELIST_FETCHING",
    MAGICTOWNS_PROFILELIST_ERROR: "MAGICTOWNS_PROFILELIST_ERROR",
}

export default magicTownsProfileListConstants;